server {
  listen 80;

  client_max_body_size 10m;
  root /home/isucon/private_isu/public/;

  location ~ ^/(css|js|img)/ {
    try_files $uri =404;
    expires 1h;
    add_header Cache-Control "public";
  }

  location = /favicon.ico {
    try_files $uri =404;
    expires 1h;
    add_header Cache-Control "public";
  }

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://localhost:8080;
  }
}
