- hosts: guests:extras
  become: yes
  gather_facts: yes
  tasks:
    - name: download data artifacts via make init
      become_user: isucon
      shell: make init
      args:
        chdir: /home/isucon/private_isu

    - name: restore postgres dump via make restore
      become_user: isucon
      shell: make restore
      args:
        chdir: /home/isucon/private_isu
