- hosts: guests:extras
  become: yes
  gather_facts: yes
  tasks:
    - name: create database and tables
      become_user: isucon
      shell: script/bootstrap
      args:
        chdir: /home/isucon/private_isu
