---
- import_playbook: 00_base.yml
- import_playbook: 01_user.yml
- import_playbook: 02_postgresql.yml
- import_playbook: 03_memcached.yml
- import_playbook: 04_nginx.yml
- import_playbook: 05_xbuild.yml
- import_playbook: 06_app.yml
- import_playbook: 07_createdb.yml
- import_playbook: 08_application.yml
- import_playbook: 10_build_benchmarker.yml
